version: "3.8"
services:
  front-page_frontend:
    container_name: shopify_front-page_frontend
    image: ghcr.io/gordonpn/shopify_front-page_frontend:stable
    environment:
      - NODE_ENV=production
    networks:
      - shopify-challenge-network
    expose:
      - 3000
    volumes:
      - caddy-shopify-front-page:/data
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  shoppies_frontend:
    container_name: shopify_shoppies_frontend
    image: ghcr.io/gordonpn/shopify_shoppies_frontend:stable
    environment:
      - NODE_ENV=production
    networks:
      - shopify-challenge-network
    expose:
      - 3000
    volumes:
      - caddy-shopify-shoppies:/data
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  proxy:
    container_name: shopify_proxy
    image: ghcr.io/gordonpn/shopify_proxy:stable
    networks:
      - shopify-challenge-network
      - traefik-public
    expose:
      - 80
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.shopify.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

volumes:
  caddy-shopify-front-page:
    name: caddy-shopify-front-page
  caddy-shopify-shoppies:
    name: caddy-shopify-shoppies

networks:
  shopify-challenge-network:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
